[viewer]
    Title = "Bonnenult's Blog"
    Description = "Bonnenult's Blog"
    Navigation = ["首页","/", "公告","/notice", "置顶","/top", "归档","/pigeonhole"]
    Bilibili = "/" # User homepage link of a video website
    Github = "https://github.com/lyljd"
    Avatar = "/resource/images/avatar.jpeg"
    UserName = "Bonnenult"
    UserDesc = "Talk is cheap, show me the code."
[system]
    Username = "admin" # your login account
    Password = "123456" # your login password
    NickName = "Bonnenult" # The name displayed in the upper right corner when logging in

    #You need to register on valine. If you don't want to use it, you can close it
    Valine = false # Open comment area
    ValineAppid = ""
    ValineAppkey = ""